/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MLModel */

#ifndef _Included_MLModel
#define _Included_MLModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MLModel
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MLModel_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     MLModel
 * Method:    close
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_MLModel_close
//  (JNIEnv *, jclass);

/*
 * Class:     MLModel
 * Method:    forward
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_MLModel_forward
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
